apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gateway-processor-26682
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/gateway-processor-26682
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
